### ISSUE TITLE
Tag new version with Swift Package Manager Package.swift

### ISSUE THREAD

**Issue by StefanNienhuis** [g-mark/SwiftPath#20]
Hi there,

While trying to use this library with the Swift Package Manager, I was getting some errors saying that the Package.swift manifest was missing for version 0.2.0. I looked at the tag on GitHub, and indeed the Package.swift file was missing. It also seems the latest tag is a lot of commits behind develop. A workaround for the SPM is to use the develop branch, but this doesn't have the version management. Would you mind tagging a new release so SPM can use its version management?

Thanks a lot,

Stefan Nienhuis

**Comment by g-mark** [comment]
Hi Stefan,

Thanks for catching that.  I just brought everything up to date, and tagged it version 0.3.1.

Let me know how it goes.

Steven
